INSERT INTO USER (USER_NO, USER_ID) values (1,'pi.big');
INSERT INTO USER (USER_NO, USER_ID) values (2,'jayden.g');
INSERT INTO USER (USER_NO, USER_ID) values (3,'nick.name');
INSERT INTO USER (USER_NO, USER_ID) values (4,'jeff.nj');
INSERT INTO USER (USER_NO, USER_ID) values (5,'hans.v');
INSERT INTO USER (USER_NO, USER_ID) values (6,'simon.w');
INSERT INTO USER (USER_NO, USER_ID) values (7,'dino.s');
INSERT INTO USER (USER_NO, USER_ID) values (8,'cosette.pick');
INSERT INTO USER (USER_NO, USER_ID) values (9,'grace.hye');
